### PR TITLE
Enhance Markdown styles

### PR DESCRIPTION
**Pull request by chadoh**
Fixes AutarkLabs/planning-suite#740

- [x] Ensure links use [`SafeLink`](https://ui.aragon.org/safe-link/)
- [x] Enhance rendering of checkbox for markdown; use [`Checkbox`](https://ui.aragon.org/check-box/)
- [x] Double check how the list / bullets work, make sure the spacing looks right
- [x] Try to break it
- [x] Match GitHub's `h1` & `h2` styles

I've also [switched](https://github.com/AutarkLabs/aragon-home/pull/16/commits/3cbc6190b551c3b2d0b73bcba77ab044f5dd3926) from [markdown-react-js](https://github.com/alexkuz/markdown-react-js) (built on top of [markdown-it](https://github.com/markdown-it/markdown-it))to [react-markdown](https://github.com/rexxars/react-markdown) (built on top of [remark](https://github.com/remarkjs/remark)). `react-markdown` has more stars, forks, and, perhaps most importantly, recently-addressed issues than `markdown-react-js`. It also talks about cross-site scripting prevention in its readme, which I appreciate. 

**Note:** I have not performed a full security audit, nor do I currently feel equipped to do so. We need to do this before we deploy to mainnet!

### code blocks

code blocks

### double-spaced lists, nested lists, blockquotes, images

double-spaced lists, nested lists, blockquotes, images

### headings, lists, xss prevention

headings, lists, xss prevention

### ordered and unordered nested lists, images

ordered and unordered nested lists, images

### tables, task lists

tables, task lists

### CODE REVIEW

**Comment by chadoh** [comment]
Given this input:

```
0. Item 1
1. Test
2. Test
   - [ ] bullet under list
      - [ ] bullet
3. Test
4. Test
   1. Test

* Test
* Test
  * Test
1. Test
2. Test
   * Test
     -  bullet  
```

Here's what it looks like *on GitHub*:

0. Item 1
1. Test
2. Test
   - [ ] bullet under list
      - [ ] bullet
3. Test
4. Test
   1. Test

* Test
* Test
  * Test
1. Test
2. Test
   * Test
     -  bullet  

And here's what it looks like with this new stylesheet:

home app rendering

**Comment by chadoh** [comment]
With the newest changes, here's what your test looks like, @stellarmagnet:

Screen Shot 2019-05-30 at 11 13 54

**Review by Quazia — APPROVED** [review]
This looks great. I like that you're using the Checkbox and SafeLink from aragon/ui. The checkbox doesn't seem to update when I click on it, I know sometimes in rendered markdown the checkbox is actually active (github issues) but I think for our use case it makes sense for them to be static. I think allowing that may be overkill here since it would require updating the whole blurb so I don't think this is an outright issue, and definitely not something we should address in the scope of the styling tweaks. It may be something that comes up in other use cases though. Also, I see you're switching the dependency we rely on for markdown, since the markdown editor is something that Aragon Black also has interest in can you explain the decision to go with this dependency briefly in the shared keybase?  I see there are some linting issues but they're addressed upstream so we can push this through but obviously in general having CI pass is good.

**Comment by chadoh** [comment]
> it would require updating the whole blurb so I don't think this is an outright issue, and definitely not something we should address in the scope of the styling tweaks

exactly

> switching the dependency we rely on for markdown

I explained this in [the commit message](https://github.com/AutarkLabs/aragon-home/pull/16/commits/3cbc6190b551c3b2d0b73bcba77ab044f5dd3926) and discussed with @ottodevs before committing. Which shared Keybase should I discuss this in, to let Aragon Black weigh in on the decision?

> I see there are some linting issues but they're addressed upstream so we can push this through but obviously in general having CI pass is good

👍

**Comment by stellarmagnet** [comment]
We need to verify how the heading styles render and try to have parity with Github.

For example, h1 currently looks like this:
image

Where it should look like this:
image

**Comment by chadoh** [comment]
I discussed with @bpierre whether we should replace `em` with `px` before merging this PR, and he does not think that seems necessary. As we help implement generic Markdown components for aragonUI, we can use styles directly from other aragonUI components at that time, as [discussed here](https://github.com/aragon/aragon-ui/issues/386#issuecomment-498322058). Note that at that time, the decision of whether to use `em` or `px` will not live in any Markdown component directly, but will be imported from other Text components.

**Pull request merged**
